name: dhmodule
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin:
  dhplugin:
    git:
      url: "git@github.com:shehabic/dhplugin.git"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidPackage: com.deliveryhero.pandora.dhmodule
    iosBundleIdentifier: com.deliveryhero.pandora.dhmodule
